### ISSUE TITLE
devDependencies or dependencies

### ISSUE THREAD

**Issue by CoqRogue** [NordicSemiconductor/pc-nrfconnect-rssi#7]
Shouldn't chart.js, react-bootstrap-slider, react-chartjs-2, bootstrap, and jQuery be dependencies instead of being devDependencies? Normal use would indicate a requirement of them, not just for development.

**Comment by mrodem** [comment]
I believe these dependencies are only required during development. All code, including code from the dependencies, are currently bundled to ./dist/bundle.js by webpack. This file will be published together with the package on npm.

If we move from devDependencies to dependencies, chart.js, react-bootstrap-slider, et al. will be installed on the user's computers even though they are already in ./dist/bundle.js.
